/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ulangansemester;
import java.text.DecimalFormat;
import java.text.NumberFormat;
import java.util.StringTokenizer;
import java.util.Locale;
/**
 *
 * @author Fujitsu
 */
public class kasir_simpel extends javax.swing.JFrame {
    String pilihan = "";
    int harga_kopi;
    int jml_harga;
    int bayar, beli, harga;
    
    /**
     * Creates new form kasir_simpel
     */
    public kasir_simpel() {
        initComponents();
        
        
              
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txthrg = new javax.swing.JTextField();
        txtjumlahbeli = new javax.swing.JTextField();
        txtjumlahbayar = new javax.swing.JTextField();
        txtbayar = new javax.swing.JTextField();
        txtkembalian = new javax.swing.JTextField();
        Combopilihan = new javax.swing.JComboBox<>();
        btnbatal = new javax.swing.JButton();
        btnkeluar = new javax.swing.JButton();
        btnhitungjumlah = new javax.swing.JButton();
        btnkembalian = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 0, 0));
        setBounds(new java.awt.Rectangle(12, 0, 0, 0));
        getContentPane().setLayout(null);

        jLabel1.setText("Nama Produk");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 10, 80, 14);

        txthrg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txthrgActionPerformed(evt);
            }
        });
        getContentPane().add(txthrg);
        txthrg.setBounds(110, 50, 120, 30);

        txtjumlahbeli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtjumlahbeliActionPerformed(evt);
            }
        });
        getContentPane().add(txtjumlahbeli);
        txtjumlahbeli.setBounds(110, 90, 120, 30);
        getContentPane().add(txtjumlahbayar);
        txtjumlahbayar.setBounds(110, 130, 120, 30);
        getContentPane().add(txtbayar);
        txtbayar.setBounds(110, 190, 120, 30);
        getContentPane().add(txtkembalian);
        txtkembalian.setBounds(110, 230, 120, 30);

        Combopilihan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Menu pilihan:", "Capucchino", "Moccachino", "Expreso", "Latte" }));
        Combopilihan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CombopilihanActionPerformed(evt);
            }
        });
        getContentPane().add(Combopilihan);
        Combopilihan.setBounds(110, 10, 120, 20);

        btnbatal.setIcon(new javax.swing.ImageIcon("C:\\Users\\Fujitsu\\Desktop\\5.png")); // NOI18N
        btnbatal.setText("Batal");
        btnbatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbatalActionPerformed(evt);
            }
        });
        getContentPane().add(btnbatal);
        btnbatal.setBounds(240, 10, 120, 50);

        btnkeluar.setIcon(new javax.swing.ImageIcon("C:\\Users\\Fujitsu\\Desktop\\1.png")); // NOI18N
        btnkeluar.setText("Keluar");
        btnkeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnkeluarActionPerformed(evt);
            }
        });
        getContentPane().add(btnkeluar);
        btnkeluar.setBounds(240, 70, 120, 50);

        btnhitungjumlah.setIcon(new javax.swing.ImageIcon("C:\\Users\\Fujitsu\\Desktop\\Untitled-1.png")); // NOI18N
        btnhitungjumlah.setText("Hitung");
        btnhitungjumlah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhitungjumlahActionPerformed(evt);
            }
        });
        getContentPane().add(btnhitungjumlah);
        btnhitungjumlah.setBounds(240, 130, 120, 50);

        btnkembalian.setIcon(new javax.swing.ImageIcon("C:\\Users\\Fujitsu\\Desktop\\2.png")); // NOI18N
        btnkembalian.setText("Kembalian");
        btnkembalian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnkembalianActionPerformed(evt);
            }
        });
        getContentPane().add(btnkembalian);
        btnkembalian.setBounds(240, 190, 120, 50);

        jLabel2.setText("Harga");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 60, 90, 14);

        jLabel3.setText("Jumlah beli");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 100, 70, 14);

        jLabel4.setText("jumlah Harga");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 140, 80, 14);

        jLabel5.setText("Harga Bayar");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(10, 200, 80, 14);

        jLabel6.setText("Jumlah Kembalian");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(10, 240, 90, 14);

        jLabel8.setIcon(new javax.swing.ImageIcon("C:\\Users\\Fujitsu\\Desktop\\1111.png")); // NOI18N
        getContentPane().add(jLabel8);
        jLabel8.setBounds(230, 240, 130, 140);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txthrgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txthrgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txthrgActionPerformed

    private void txtjumlahbeliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtjumlahbeliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtjumlahbeliActionPerformed

    private void CombopilihanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CombopilihanActionPerformed
        // TODO add your handling code here:
        pilihan=(String)Combopilihan.getSelectedItem();
        switch(pilihan){
            case"Capucchino":
            harga_kopi=10000;
            break;
            case"Moccachino":
            harga_kopi=12000;
            break;
            case"Expreso":
            harga_kopi=15000;
            break;
            case"Latte":
            harga_kopi=16000;
            break;
        }
        txthrg.setText(""+Integer.toString(harga_kopi));
    }//GEN-LAST:event_CombopilihanActionPerformed

    private void btnkembalianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnkembalianActionPerformed
        // TODO add your handling code here:
        int harga_bayar=Integer.parseInt(txtbayar.getText());
        int total=harga_bayar-bayar;
        
        txtkembalian.setText("Rp. "+Integer.toString(total));
    }//GEN-LAST:event_btnkembalianActionPerformed

    private void btnhitungjumlahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhitungjumlahActionPerformed
        // TODO add your handling code here:
        harga=Integer.parseInt(txthrg.getText());
        beli=Integer.parseInt(txtjumlahbeli.getText());
        
        bayar=harga*beli;
        DecimalFormat angka = new DecimalFormat("###,###");
        txtjumlahbayar.setText(""+Integer.toString(bayar));
    }//GEN-LAST:event_btnhitungjumlahActionPerformed

    private void btnkeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnkeluarActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnkeluarActionPerformed

    private void btnbatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbatalActionPerformed
        // TODO add your handling code here:
        
        txtjumlahbeli.setText("");
        txtjumlahbayar.setText("");
        txtbayar.setText("");
        txthrg.setText("");
        txtkembalian.setText("");
        Combopilihan.setSelectedIndex(0);
    }//GEN-LAST:event_btnbatalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(kasir_simpel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(kasir_simpel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(kasir_simpel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(kasir_simpel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new kasir_simpel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Combopilihan;
    private javax.swing.JButton btnbatal;
    private javax.swing.JButton btnhitungjumlah;
    private javax.swing.JButton btnkeluar;
    private javax.swing.JButton btnkembalian;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField txtbayar;
    private javax.swing.JTextField txthrg;
    private javax.swing.JTextField txtjumlahbayar;
    private javax.swing.JTextField txtjumlahbeli;
    private javax.swing.JTextField txtkembalian;
    // End of variables declaration//GEN-END:variables
}
